package com.phizercost.biblequiz.utils;

public enum BibleQuizUtils {
	TEAM_NAMES_NOT_SET("AMAZINA Y'AMATSINDA YOMBI  AGOMBA KWANDIKWA KANDI NTABWO YEMEREWE GUHUZA AMAZINA"),
	INITIALIZE_GAME("TANGIRA"),
	MAIN_TITLE("BIBLE QUIZ FESTIVAL 2017"),
	QUICK_QUESTIONS_TITLE("UMUVUDUKO"),
	CATEGORY_QUESTIONS_TITLE("IBYICIRO"),
	HINT_QUESTIONS_TITLE("AGATOKI"),
	BONUS_QUESTIONS_TITLE("INYONGEZO"), 
	GET_QUESTION_TITLE("IKIBAZO"),
	GET_ANSWER_TITLE("IGISUBIZO"),
	GET_WAIT_TITLE("TEGEREZA"),
	GET_CONTINUE_TITLE("KOMEZA"),
	GET_SCORE_TITLE("UTSINDIYE"),
	GET_HINT_TITLE("AGATOKI"),
	TIME_OVER("BYARANGIYE");
	
	
	private final String string;
	
	private BibleQuizUtils(String string) {
		this.string = string;
	}
	
	public String getString() {
		return this.string;
	}
}
